#!/bin/bash

function main(){

	execpath=$(dirname $(realpath $0))
	cd "$execpath/aide"

	cat > aide.conf <<EOF
database=file:aide.db
database_out=file:aide.db
gzip_dbout=no
verbose=2
report_url=file:aide.log
report_url=stdout
MONITORING=md5+p+u+g+m
EOF

	monitor_list=$(cat $execpath/monitor.list|grep -E '^/')
	echo "--------------------------"
	echo "Monitoring Directory List:"
	echo "--------------------------"
	for i in $monitor_list
	do
		echo "$i"
		echo "$i MONITORING">> aide.conf
	done

	exclude_list=$(cat $execpath/exclude.list |grep -E '^/')
	echo "------------------"
	echo "Exclude File List:"
	echo "------------------"
	for i in $exclude_list
	do
		echo "$i"
		echo "!$i">> aide.conf
	done
	
	echo "------------------"
	echo "create baseline..."
	./aide -c aide.conf --init
	echo "baseline complete"
	
}

main
